booking as guest now works. lil style tweaks

diff --git a/Dockerfile.cms b/Dockerfile.cms
--- a/Dockerfile.cms
+++ b/Dockerfile.cms
@@ -19,16 +19,16 @@ RUN \
     echo "Lockfile not found." && exit 1; \
   fi
 
-# RUN \
-#   if [ -f yarn.lock ]; then \ 
-#     yarn generate; \
-#   elif [ -f package-lock.json ]; then \ 
-#     npm generate; \
-#   elif [ -f pnpm-lock.yaml ]; then \ 
-#     pnpm generate; \
-#   else \ 
-#     echo "Lockfile not found." && exit 1; \
-#   fi
+RUN \
+  if [ -f pnpm-lock.yaml ]; then \ 
+    pnpm generate; \
+  elif [ -f package-lock.json ]; then \ 
+    npm generate; \
+  elif [ -f yarn.lock ]; then \ 
+    yarn generate; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN \
   if [ -f pnpm-lock.yaml ]; then \ 
@@ -58,6 +58,8 @@ ENV NEXT_TELEMETRY_DISABLED 1
 FROM base AS runner
 WORKDIR /app
 
+# COPY --from=builder /app .
+COPY --from=builder /app/.env.prod ./.env
 COPY --from=builder /app/package.json ./package.json
 COPY --from=builder /app/pnpm-lock.yaml .
 
@@ -82,5 +84,10 @@ ENV PORT 3001
 # RUN npx keystone prisma generate
 # RUN npx keystone postinstall
 
-CMD ["npx", "keystone", "start", "--with-migrations"]
+# RUN npx keystone prisma migrate deploy
+# CMD ["npx", "keystone", "start", "--with-migrations"]
+CMD ["sh", "-c", "npx keystone start --with-migrations"]
 # CMD ["pnpm", "ks:start"]
+# RUN npx keystone prisma generate
+# CMD npx keystone prisma migrate deploy && npx keystone start --with-migrations
+# CMD ["sh", "-c", "npx keystone prisma migrate deploy && npx keystone start --with-migrations"]
